### ISSUE TITLE
Does not work with the new semaphore features of bordeaux-threads

### ISSUE THREAD

**Issue by xach** [r-moeritz/bt-semaphore#4]
Bordeaux-threads now includes semaphores and somehow they break bt-semaphore. Could bt-semaphore be updated to work with the new bordeaux-threads semaphore feature?

**Comment by dkochmanski** [comment]
bt-semaphore has `(:use :cl :bordeaux-threads)` in its package while bordeaux-threads exports conflicting symbols. That means, that when bt-semaphore tries to define function signal-semaphore it overwrites function associated with symbol in bordeaux-threads.

Solution 1 (imo better): simply reexport symbols from BT since it has semaphroe implementation now (bt-semaphore would stay for backward compatibility with libraries depending on it)

Solution 2: do not `USE` bordeaux-threads and add proper package accessor to symbols accessed from BT (or import them one-by-one for clarity)

**Comment by rmoritz** [comment]
Thanks for reporting, and it's great that BT has semaphores now. I'll try to look into this issue sometime this week.

**Comment by quicklisp** [comment]
I hope to make a new Quicklisp release by tomorrow night - that of course does not mean you have to look at it any sooner, but it would be a bit convenient to me if you did.

**Comment by r-moeritz** [comment]
@quicklisp Done. Tested against the latest bt by cloning it into `~/quicklisp/local-projects`.
